version: 0.2
phases:
    install:
      runtime-versions:
        nodejs: 16
    pre_build:
      commands:
        - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 034362041266.dkr.ecr.ap-northeast-1.amazonaws.com
    build:
      commands:
        - echo Build started on `data`
        - npm install
        - echo npm install completed on `data`
        - npm run build
        - echo npm run build completed on `data`
        - TAG=`date "+%Y%m%d%H%M%S"`
        - docker build -t 034362041266.dkr.ecr.ap-northeast-1.amazonaws.com/test0226ecr:$TAG ./
        - echo docker build completed on `date`
        - docker push 034362041266.dkr.ecr.ap-northeast-1.amazonaws.com/test0226ecr:$TAG
        - echo docker push completed on `date`
    post_build:
      commands:
        - echo Build completed on `data`
        - printf '[{"name":"mynginx","imageUri":"%s"}]' 034362041266.dkr.ecr.ap-northeast-1.amazonaws.com/test0226ecr:$TAG > imagedefinitions.json
        - cat imagedefinitions.json
artifacts:
    files:
      - imagedefinitions.json